PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PubkeyAuthentication yes
PermitRootLogin no
AllowUsers pzagent
AuthorizedKeysFile /home/pzagent/.ssh/authorized_keys
PermitUserEnvironment yes
X11Forwarding no
AllowTcpForwarding no
PermitTunnel no
GatewayPorts no
ClientAliveInterval 60
ClientAliveCountMax 3
